version: 2
sources:
  - name: staging
    database: AIRBYTE_DATABASE
    schema: AIRBYTE_SCHEMA
    tables:
      - name: YELLOW_TRIPS_2019 
models:

  - name: yellow_tripdata
    description: > 
        Trips made by New York City's iconic yellow taxis. 
        Yellow taxis are the only vehicles permitted to respond to a street hail from a passenger in all five
        boroughs. They may also be hailed using an e-hail app like Curb or Arro.
        The records were collected and provided to the NYC Taxi and Limousine Commission (TLC) by
        technology service providers. 
    